# Generated by Django 4.1.5 on 2023-01-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ip',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
