# Generated by Django 4.1.5 on 2023-01-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_profile_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(default='eng', max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='use_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tmp',
            name='number',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='tmp',
            name='test',
            field=models.CharField(default='test', max_length=10),
        ),
    ]
