# Generated by Django 4.1.5 on 2023-02-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_profile_language_profile_use_date_tmp_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
